default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  pool: 5

development:
  <<: *default
  database: ruby_saas_task_development

test:
  <<: *default
  database: ruby_saas_task_test
